---

jobs:
  - name: datascience
    plan:
      - get: repo
        trigger: true
      - task: build-image
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: jupyter/repo2docker
              tag: 8a5b1ef
          inputs:
            - name: repo
          run:
            path: repo/ci/scripts/build-image.sh
          outputs:
            - name: build
      - put: build
        params:
          build: build
          tag_as_latest: true
          build_args:
            NB_USER: jovyan
            NB_UID: "1000"

resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/natbusa/dsp-titanic.git
      branch: master
  - name: build
    type: docker-image
    source:
      email: natalino.busa@gmail.com
      repository: registry-docker-registry.dsf.svc.cluster.local:5000/natbusa/r2d
      insecure_registries:
        - http://registry-docker-registry.dsf.svc.cluster.local:5000
